export {default as  Root} from './root/Root'
export {default as  DashBoard, loader as loaderDashBoard} from './dashboard/DashBoard'
export {default as  Hotel, loader as loaderHotels, action as actionDeleteHotel} from './hotels/Hotel.jsx'
export {default as NewHotel} from './newHotel/NewHotel'
export {default as EditHotel, loader as loaderEditHotel} from './editHotel/EditHotel'
export {default as NewRoom, loader as loaderNewRoom} from './newRoom/NewRoom'
export {default as Room, loader as loaderRooms, action as actionDeleletRoom} from './rooms/Room'
export {default as  Authentication, action as actionAuth} from './auth/Authentication'
export {default as EditRoom, loader as loaderEditRoom } from './editRoom/EditRoom'
export {default as Transaction, loader as loaderTransaction} from './transaction/Transaction'
export {action as actionLogout} from './logout/Logout'
